### ISSUE TITLE
ImportError: dynamic module does not define init function (init_tf2)

### ISSUE THREAD

**Issue by Gaurav37** [furushchev/respeaker_ros#30]
When I launch respeaker.launch, it gives me error:

NODES
  /
    respeaker_node (respeaker_ros/respeaker_node.py)
    speech_to_text (respeaker_ros/speech_to_text.py)
    static_transformer (tf/static_transform_publisher)

ROS_MASTER_URI=http://localhost:11311

process[respeaker_node-1]: started with pid [68053]
process[static_transformer-2]: started with pid [68054]
process[speech_to_text-3]: started with pid [68055]
Traceback (most recent call last):
  File "/home/gaurav/catkin_ws2/src/respeaker_ros/scripts/respeaker_node.py", line 12, in <module>
    import tf.transformations as T
  File "/opt/ros/noetic/lib/python3/dist-packages/tf/__init__.py", line 30, in <module>
    from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException
  File "/opt/ros/noetic/lib/python3/dist-packages/tf2_ros/__init__.py", line 38, in <module>
    from tf2_py import *
  File "/opt/ros/noetic/lib/python3/dist-packages/tf2_py/__init__.py", line 38, in <module>
    from ._tf2 import *
ImportError: dynamic module does not define init function (init_tf2)
[respeaker_node-1] process has died [pid 68053, exit code 1, cmd /home/gaurav/catkin_ws2/devel/lib/respeaker_ros/respeaker_node.py __name:=respeaker_node __log:=/home/gaurav/.ros/log/a317667e-c4b7-11ec-bb11-8df75aa53f77/respeaker_node-1.log].
log file: /home/gaurav/.ros/log/a317667e-c4b7-11ec-bb11-8df75aa53f77/respeaker_node-1*.log
Traceback (most recent call last):
  File "/home/gaurav/catkin_ws2/src/respeaker_ros/scripts/speech_to_text.py", line 5, in <module>
    import actionlib
  File "/opt/ros/noetic/lib/python3/dist-packages/actionlib/__init__.py", line 28, in <module>
    from actionlib.action_client import *
  File "/opt/ros/noetic/lib/python3/dist-packages/actionlib/action_client.py", line 56, in <module>
    import rospy
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 49, in <module>
    from .client import spin, myargv, init_node, \
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/client.py", line 60, in <module>
    import rospy.impl.init
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/init.py", line 54, in <module>
    from .tcpros import init_tcpros
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros.py", line 45, in <module>
    import rospy.impl.tcpros_service
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_service.py", line 54, in <module>
    from rospy.impl.tcpros_base import TCPROSTransport, TCPROSTransportProtocol, \
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 167
    (e_errno, msg, *_) = e.args
                   ^
SyntaxError: invalid syntax
[speech_to_text-3] process has died [pid 68055, exit code 1, cmd /home/gaurav/catkin_ws2/devel/lib/respeaker_ros/speech_to_text.py audio:=speech_audio __name:=speech_to_text __log:=/home/gaurav/.ros/log/a317667e-c4b7-11ec-bb11-8df75aa53f77/speech_to_text-3.log].
log file: /home/gaurav/.ros/log/a317667e-c4b7-11ec-bb11-8df75aa53f77/speech_to_text-3*.log
^C[static_transformer-2] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by JohannaPrinz** [comment]
I have the exact same Problem/Error - what can I do to solve it? @furushchev
